### ISSUE TITLE
RSMM hangs when entering Play Solo, vanilla Studio does not

### ISSUE THREAD

**Issue by Kampfkarren** [CloneTrooper1019/Roblox-Studio-Mod-Manager#29]
When clicking Play Solo on RSMM on an empty Baseplate regardless of APS, Studio hangs and requires a force kill from Task Manager. Vanilla Studio does not have this issue.

**Comment by EchoReaper** [comment]
Talked with Clone and apparently this is due to RSMM not removing files when they are removed from the Studio directory. If you delete your RSMM Studio install and re-install, the issue will be fixed.

**Comment by Kampfkarren** [comment]
...Or it did? I wiped my entire folder 3 times and now it started working. Huh.

**Comment by CloneTrooper1019** [comment]
I will have a new version out that cleans up old files soon. Working on a big patch to supersede my now broken fflag scanner.

**Comment by EchoReaper** [comment]
@CloneTrooper1019 One of the use cases I have for RSMM is that I can place local audio/image/etc files in the content folder and not have to worry about Roblox clearing it every time it updates. I don't use ModFiles since I have to restart Studio for those to take effect.

**Comment by CloneTrooper1019** [comment]
@EchoReaper That's fair. In my use case I have a specific StarterScript setup that lets me load in my own modules while still running the actual StarterScript. Since Roblox can overwrite that file with its own changes, I have to keep it in my mod folder.

One thing that I might look into is introducing a live update feature of sorts, where you can edit a file in the mod folder and the mod manager will try to mirror it into studio's directory automatically, if it has the edit permissions to do so.
