### ISSUE TITLE
Support builds older than 9/9/2019

### ISSUE THREAD

**Issue by ReinitiaIized** [CloneTrooper1019/Roblox-Studio-Mod-Manager#49]
An use case for this is currently how ROBLOX Studio handles Asset Configuration, making it nearly impossible to update Assets which are past a certain number. Although this has been brought up in the Devforums, there's been no progress since August 2019. It'd be nice to revert back to a build before then to utilize the previous gen Asset Configuration without having to download the deployment files manually.

**Comment by CloneTrooper1019** [comment]
I set a minimum version because builds prior to changelist 340802 are not compliant with the technique I use to disambiguate 32-bit builds from 64-bit builds of Roblox Studio. If you scroll all the way down on this page, you’ll notice that they started labeling 64-bit builds of Roblox Studio as Studio64 around 9/16/2019:

https://s3.amazonaws.com/setup.roblox.com/DeployHistory.txt

Before they started doing this, I had to do some awkward prediction logic to figure out which deploy log is the latest for 64-bit builds, and which is the latest for 32-bit builds. It was messy and buggy, and it’s hard to provide compatibility for both.

Ultimately, this feature isn’t intended for people to rollback to earlier production builds, its intended for specific sitetest builds to be targeted for testing, in the event Roblox adds a cool new feature, but has to roll it back because issues were discovered and it wasn’t ready for production.
