### ISSUE TITLE
Wacatac trojan?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [CloneTrooper1019/Roblox-Studio-Mod-Manager#53]
Before I start it, it says that my antivirus found Wacatac c ml trojan inside the exe.

**Comment by CloneTrooper1019** [comment]
Wacatac c ml? What antivirus are you using?
It makes sense that an antivirus program would get mad at the program since the code is unsigned, but there’s no trojan in my code.

**Comment by squidiskoolchaos** [comment]
Windows Defender.

**Comment by CloneTrooper1019** [comment]
Yikes, well this is interesting. I wonder if it’s actually on my PC somehow. I will take this seriously and investigate. If you have any extra information it would be greatly appreciated.

**Comment by databasetd** [comment]
Looking at the code, the detections are most likely caused by the program's behavior. Antivirus programs generally aren't too fond of apps it doesn't recognize doing things like modifying registry keys or reading/writing in the AppData folder.

Looking at VirusTotal results it seems to be falsely flagged as adware: https://www.virustotal.com/gui/file/2057cd867350fb5925de3c378012268ac69c3d4959ba50b5130bacd4a5b9e11e/detection

**Comment by CloneTrooper1019** [comment]
After some deeper analysis, I think I can safely confirm this is a false alarm.
https://devforum.roblox.com/t/roblox-studio-mod-manager/12572/26?u=clonetrooper1019

I rebuilt the program on my desktop today, and while the Wacatac trojan label disappeared, it did start reporting something about an MSIL/Perseus trojan. However, I also scanned the application behind my Roblox Client Tracker and API Dump Tool after rebuilding them on my PC today, and only one generic "suspicious" result showed up for those two. 

The client tracker itself derives a lot of code from this project, so for it to not report anything despite doing way more stuff on my system seems to put this detection into question.

I'm still inconclusive, but I suspect my program is repeating some sort of pattern or behavior that was observed in this MSIL/Perseus trojan, and its falsely flagging the program as such.

If any of you have information that might prove this argument otherwise, please let me know as soon as possible, otherwise I think I can say this is resolved.
