### ISSUE TITLE
Skip Mod Manager window and directly open place?

### ISSUE THREAD

**Issue by blake-mealey** [CloneTrooper1019/Roblox-Studio-Mod-Manager#77]
Hey, I'm curious if there's a way I can open a place file with mod manager directly? I'd like to setup a command line like "roblox" which I can run to open place files with this ModManager. I'm thinking I'd just use Windows Shortcuts - does this project currently support and command-line flags to skip the ModManager window and go straight to studio or to directly open a place file?

Thanks

**Comment by CloneTrooper1019** [comment]
It does pass the arguments along to studio as they were passed into the exe.
The installation directory is constant, so you could simply point it to `%localappdata%\Roblox Studio\RobloxStudioBeta.exe`

**Comment by Aiden-12114** [comment]
@CloneTrooper1019 I was wondering if I replace `RobloxStudioBeta.exe` with the Mod Manager and name it the same, could I just open it like normal?

**Comment by CloneTrooper1019** [comment]
@Aiden-12114 No. Launches have to go through the mod manager because Roblox's own bootstrapper overwrites any modified files.

**Comment by CloneTrooper1019** [comment]
I'm going to close this issue for now, if you have any additional questions feel free to follow up and let me know!

**Comment by LewisTehMinerz** [comment]
Request that does relate to this issue.
Mod manager registers its association with the `roblox-studio` protocol so that it can be launched when you edit a place from the website:
![image](https://user-images.githubusercontent.com/8019327/107944996-e4365980-6f86-11eb-9e13-21fd39960fca.png)
However it does not launch Roblox Studio immediately, instead showing the bootstrapper where you then have to click `Launch Studio` separately. My request would be to check the flags that are passed, and if they are to edit a place from the site, just launch studio without showing the bootstrapper first. RSMM does this for local place files already, however I don't know what the flags are that the website passes on.
