### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by AKASGaming** [CloneTrooper1019/Roblox-Studio-Mod-Manager#91]
I don't know if I'm missing something that may be required to run the Mod Manager, but I had to use [this version](https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/releases/tag/v2020.6.10) to even get it to open.

_I'm running Windows 7 x64_

**Comment by CloneTrooper1019** [comment]
Since Windows 7 reached its EOL early last year, I don’t really have much control over whether it’ll be compatible going forward. As far as I’m aware I haven’t made any changes that would explicitly stop the program from working in older versions of Windows, but I do build it on a machine running Windows 10.
